### ISSUE TITLE
Pretrained model

### ISSUE THREAD

**Issue by IbrH** [ZhengPeng7/MCCL#1]
Where can I find a pretrained model for your architecture? Thanks in advance!

**Comment by ZhengPeng7** [comment]
Hi bro, glad to see your interest. I rent a machine online for these experiments at that time, but I didn't realize the machine was in arrears and the instance was released. However, I found weights@epoch120 in another machine, and the results are almost the same as the original one as below, you can have a comparison between them. I've added the weights and predicted maps in the [release](https://github.com/ZhengPeng7/MCCL/releases/tag/v0.7) and the [links on google-drive](https://drive.google.com/drive/u/0/folders/1zH1biBDPCA0u2PJSQCeJTY9csnKFeY39).
| Dataset | maxEm | Smeasure | maxFm |  MAE  | meanEm | meanFm | adpEm | wFmeasure | adpFm |
| :-------: | :-------: | :------: | :------: | :-------: | :-------: | :-------: | :-------: | :-------: | :-------: |
|   CoCA  | 0.796 |  0.713   | 0.584 | 0.097 | 0.763  | 0.559  | 0.757 |   0.513   | 0.548 |
| CoSOD3k | 0.902 |  0.854   | 0.832 | 0.061 | 0.878  | 0.808  | 0.861 |   0.778   | 0.783 |
| CoSal2015 | 0.924 |  0.887   | 0.887 | 0.053 | 0.907  | 0.867  | 0.873 |   0.848   | 0.827 |
