### ISSUE TITLE
读取coco-seg数据问题

### ISSUE THREAD

**Issue by Wuhuddy** [ZhengPeng7/MCCL#2]
您好，在运行您代码中的train.py，或者其他使用coco-seg作为训练集的代码时，总会随机出现读取图片的错误，请问您知道原因是什么吗？
![bug](https://github.com/ZhengPeng7/MCCL/assets/121659356/3c9b6d93-69d4-4690-9f15-f2f3c4691274)

**Comment by ZhengPeng7** [comment]
Hi, 是指使用我的代码会随机出现这个问题, 还是其他代码都可能会出现呢?

**Comment by Wuhuddy** [comment]
> Hi, 是指使用我的代码会随机出现这个问题, 还是其他代码都可能会出现呢?

您好，只要是用coco-seg训练就会出现，coco9213就不会

**Comment by ZhengPeng7** [comment]
我这里确实是没有耶, 那你看下是不是每次都是这个文件呢? 当然你说是随机, 所以有可能不是.
或者你可以从我[google-drive](https://drive.google.com/file/d/1-BYf8oj30LF_55fpow6eo3yD5n0h3DTE/view?usp=drive_link)/[百度网盘(pw: ccsg)](https://pan.baidu.com/s/1yX8rHxizYHSJj5viBbfnSw)重新下载一下coco-seg, 然后来重新run下看看.

**Comment by Wuhuddy** [comment]
> 

ok，我尝试一下，感谢您

**Comment by Wuhuddy** [comment]
![1](https://github.com/ZhengPeng7/MCCL/assets/121659356/572dc13c-d7cb-44fe-8ed0-27653cf4a944)
您好，请问这行代码的目的是什么，debug出来两次scaled_preds都是一样的值。

**Comment by ZhengPeng7** [comment]
一样才是正确的, 因为这里的一些功能/模块没开启, 这时应该保持不变.

**Comment by Wuhuddy** [comment]
好的谢谢

**Comment by Wuhuddy** [comment]
请问在训练时，两个数据集的loss是分别通过各自的sal_loss()函数计算，然后在batch_seg这块的loss_log.update()中进行相加吗？
![1](https://github.com/ZhengPeng7/MCCL/assets/121659356/013972b8-9681-4eb8-90ac-5e93ecfc1873)

**Comment by ZhengPeng7** [comment]
嗯, 你说的没错.

**Comment by Wuhuddy** [comment]
感谢！

**Comment by Wuhuddy** [comment]
您好，很抱歉周末打扰您。请问论文中MCM模块的通过动量更新一致性特征这一块在代码中有体现吗，我理解下来好像就是每次batch前清空，然后计算后输给norm_feature？

**Comment by ZhengPeng7** [comment]
不客气, 就是您理解的这样的. 动量变大之前效果不是很显著, 这样子比较好, 就没有放到主codebase里. 当时代码比较混乱, 去年有两个月比较划水没跑实验, 结果在autodl上的实例被释放了, 有些材料还有权重就丢了 [issue-1](https://github.com/ZhengPeng7/MCCL/issues/1#issuecomment-1464051744). 但是后来我自己重新run, performance还是能轻易达到一致的.

**Comment by Wuhuddy** [comment]
了解，感谢您的回复！
