### ISSUE TITLE
一些请教

### ISSUE THREAD

**Issue by zhending111** [ZhengPeng7/MCCL#3]
为什么找不到MCM模块？以及是否真正用了对比学习？

**Comment by ZhengPeng7** [comment]
Hi, 感谢你的兴趣, 严格来说确实这里确实有一点不相符, 这个我在之前的问题里提到: [#2 ](https://github.com/ZhengPeng7/MCCL/issues/2#issuecomment-1657158030). 对比学习是没有问题的, 并且可以将group的数量给调高, 但是实验比较相差不大, 反而训练速度会慢下来. 这个proj做的比较乱, 如果是想继续cosod的话, 还是推荐我之前的[GCoNet+](https://github.com/ZhengPeng7/GCoNet_plus), 效果更好, 文档更全, 甚至每个ablation study的权重和结果图都有提供.

如果后续还有任何问题, 欢迎继续留issue或email我, 我一般看到随时回.

**Comment by zhending111** [comment]
好的，非常感谢

**Comment by ZhengPeng7** [comment]
Feel free to reopen it if you have any other questions.

**Comment by liaochuanlin** [comment]
可以提供这个MCM部分的代码吗？
