### ISSUE TITLE
数据下载问题 

### ISSUE THREAD

**Issue by liaochuanlin** [ZhengPeng7/MCCL#4]
我在谷歌云盘下载的时候出现配额限制，作者可以把数据用百度云链接发送到我的邮箱吗？2651106983@qq.com

**Comment by ZhengPeng7** [comment]
数据集的百度云链接我今天晚上前会添加到README里了, 欢迎届时check.

**Comment by ZhengPeng7** [comment]
链接已添加, 可以去下载啦.

**Comment by liaochuanlin** [comment]
First, we take images of N (default as 2) groups as the input {G1, G2, ..., GN }. We concatenate all the images as a whole batch G, which is then fed to the encoder. With the backbone network (default as the Transformer network PVTv2 (Wang et al. 2022)) as our encoder, embedded features are extracted as F, which is then split by their group categories as {F1, F2, ..., FN }, where FN = {FN,s}sS=1 ∈ RS×C×H×W , C denotes the channel number, H ×W means the spatial size, and N is the group size. Meanwhile, the intermediate features {F lat 1 , F lat 2 , F lat 3 } at different stages of our encoder are saved and fed to their corresponding stages of the decoder by a 1x1 convolutional layer.
这段话中的S表示的类别吗？




廖川林
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ZhengPeng7/MCCL"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月19日(星期二) 下午5:27
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ZhengPeng7/MCCL] 数据下载问题  (Issue #4)





 
链接已添加, 可以去下载啦.

**Comment by liaochuanlin** [comment]
Finally, we perform depthwise correlation to fuse the original feature with the consensus feature, and concatenate them to form the final consensus representation Fout.这句话怎么理解？
只是一个concatenate操作？






廖川林
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ZhengPeng7/MCCL"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月19日(星期二) 下午5:27
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ZhengPeng7/MCCL] 数据下载问题  (Issue #4)





 
链接已添加, 可以去下载啦.

**Comment by ZhengPeng7** [comment]
你可以截个图吗? 复制过来格式都是问题, 你要不自己看一看能不能读懂? 没人那么有时间去特地去给你发邮件, 何况我也没义务整理都是公开的数据集. 目前代码和数据就这样了, 最新版本也能一次就跑到论文里的performance, 现在的code的MCM和论文确实如我这里所说有所出入: https://github.com/ZhengPeng7/MCCL/issues/3#issuecomment-1904046890.

**Comment by liaochuanlin** [comment]
不好意思 没有注意到这个问题&nbsp;
&nbsp;


廖川林
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jinheng ***@***.***&gt;; 
发送时间: 2024年3月20日(星期三) 晚上8:30
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ZhengPeng7/MCCL] 数据下载问题  (Issue #4)





 
你可以截个图吗? 复制过来格式都是问题, 你要不自己看一看能不能读懂? 没人那么有时间去特地去给你发邮件, 何况我也没义务整理都是公开的数据集. 目前代码和数据就这样了, 最新版本也能一次就跑到论文里的performance, 现在的code的MCM和论文确实如我这里所说有所出入: #3 (comment).
